import React, { Fragment, ReactNode } from 'react'
import Footer from './Footer'
import Header from './Header'
import Head from 'next/head'

type Props = {
    children: ReactNode,
    landing?: boolean
}

const Layout = ({children, landing}: Props) => {
  return (
    <>
        <Head>
            <title>RFW</title>
            <meta name="description" content="Generated by create next app" />
            <meta name="viewport" content="width=device-width, initial-scale=1" />
            <link rel="icon" href="/favicon.ico" />
            <link rel="preconnect" href="https://fonts.googleapis.com"/>
            <link rel="preconnect" href="https://fonts.gstatic.com" crossOrigin=''/>
            <link href="https://fonts.googleapis.com/css2?family=Italiana&display=swap" rel="stylesheet"/>
            <link rel="preconnect" href="https://fonts.googleapis.com"/>
            <link rel="preconnect" href="https://fonts.gstatic.com"/>
            <link href="https://fonts.googleapis.com/css2?family=IBM+Plex+Serif:wght@400;700&display=swap" rel="stylesheet"/>
        </Head>
        <Header/>
        <div className='w-full h-24'>
        </div>
        <main className={`w-full h-[745px] max-h-[1080px] ${landing != null && 'bg-star bg-no-repeat bg-cover bg-[0_-120px]'}`}>
            {children}
        </main>
        <Footer/>
    </>
  )
}

export default Layout