import Head from 'next/head'
import Image from 'next/image'
import { Inter } from 'next/font/google'
import styles from '@/styles/Home.module.css'
import Layout from '@/components/Layout'
import star from '../public/assets/star.png'
import SignUp from '@/components/SignUp'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
      <Head>
        <title>RFW</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
        <link rel="preconnect" href="https://fonts.googleapis.com"/>
        <link rel="preconnect" href="https://fonts.gstatic.com" crossOrigin=''/>
        <link href="https://fonts.googleapis.com/css2?family=Italiana&display=swap" rel="stylesheet"/>
        <link rel="preconnect" href="https://fonts.googleapis.com"/>
        <link rel="preconnect" href="https://fonts.gstatic.com"/>
        <link href="https://fonts.googleapis.com/css2?family=IBM+Plex+Serif:wght@400;700&display=swap" rel="stylesheet"/>
      </Head>
      <Layout>
        {/* <Image  style={{width: '100%', 
                        maxHeight: '1000px', 
                        objectFit: 'fill', 
                        objectPosition: '0 -100px', 
                        position: 'absolute', 
                        zIndex: '-2'
                      }}  
                src={star} 
                alt='Roanoke star'/> */}
        <SignUp/>
      </Layout>
    </>
  )
}
